// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO_sIMmbSI7SpJC7c3x0Tkvou9POwvqEE',
    appId: '1:328546295931:web:0bcd83a3e512677bee82de',
    messagingSenderId: '328546295931',
    projectId: 'ai-cv-maker-e4dd9',
    authDomain: 'ai-cv-maker-e4dd9.firebaseapp.com',
    storageBucket: 'ai-cv-maker-e4dd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxi7so-x8jIeKQ2jLqruGKVnZ-Z9kDxQ',
    appId: '1:328546295931:android:43e23a0d19afb5f2ee82de',
    messagingSenderId: '328546295931',
    projectId: 'ai-cv-maker-e4dd9',
    storageBucket: 'ai-cv-maker-e4dd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIzls8Xc2sfpTxt-0D38ZkRAphX-COZao',
    appId: '1:328546295931:ios:2428f40d9f48215cee82de',
    messagingSenderId: '328546295931',
    projectId: 'ai-cv-maker-e4dd9',
    storageBucket: 'ai-cv-maker-e4dd9.firebasestorage.app',
    androidClientId: '328546295931-k3pk0dvtodd1sijfn4u1l8sjjmbn6cfu.apps.googleusercontent.com',
    iosClientId: '328546295931-8mfc63oj41pg47doltu6tff108a847rt.apps.googleusercontent.com',
    iosBundleId: 'com.novaXccelerate.aiCvMaker',
  );
}
