import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_fonts/google_fonts.dart';

import 'firebase_options.dart'; // 🔧 Auto-generated by `flutterfire configure`
import 'screens/sign_in_screen.dart';
import 'screens/cv_form_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const CVGeneratorApp());
}

class CVGeneratorApp extends StatelessWidget {
  const CVGeneratorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CVGenerator',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        textTheme: GoogleFonts.poppinsTextTheme(), // ✅ Apply Poppins globally
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const SignInScreen(),
        '/cv_form': (context) => const CVFormScreen(),
      },
    );
  }
}
